<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Male</name>
   <tag></tag>
   <elementGuidId>cd7e5728-216b-4a41-8f0c-21ccd7b40b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'option-0') and (contains(text(), 'Male
        ') or contains(., 'Male
        '))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs4__option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs4__option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>59bd8165-c989-444d-8fe9-c47bc8e9468f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>d9b9727f-db2c-4810-9919-26ab176b6e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8d8787f6-9da2-472d-b127-8fdc83dedcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>47cfca8e-c61f-4d2f-b93f-9b02d0b38fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec34dfc6-7867-4a28-abe8-613004169705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male
        </value>
      <webElementGuid>a7f7e52a-0cd2-4647-b170-3f3b8d6f52d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__option-0&quot;)</value>
      <webElementGuid>61f8ef50-0242-4d1d-84dc-64d8dfefe9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs4__option-0']</value>
      <webElementGuid>21ed6ee3-dc14-48b7-815b-fc4382821779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs4__listbox']/li</value>
      <webElementGuid>64477cf6-3d4d-4b54-b9c9-19cab2a72115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[1]</value>
      <webElementGuid>b4272d4c-6d7a-4f95-9cd8-b660d822400b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::li[1]</value>
      <webElementGuid>f65d0ce7-e9bf-4981-8b79-1a8978567b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::li[1]</value>
      <webElementGuid>1e3ec1e2-5851-40c0-a519-2314d123077b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Male']/parent::*</value>
      <webElementGuid>b546c747-19f5-40f7-8d7e-ea23f48ac704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li</value>
      <webElementGuid>f9047533-398b-4b1d-9d45-b1e2c063c3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs4__option-0' and (text() = '
          Male
        ' or . = '
          Male
        ')]</value>
      <webElementGuid>b36da915-f377-4c0c-9e83-6e69348423f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
