<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Address Verification Will Be Completed In_d5090b</name>
   <tag></tag>
   <elementGuidId>5ac9e2ed-ab8f-4302-8917-e85bba451f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T0tBZGRyZXNzJTIwVmVyaWZpY2F0aW9uJTIwV2lsbCUyMEJlJTIwQ29tcGxldGVkJTIwSW4lMjA0OCUyMEhvdXJzZ3JlZW4']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.iziToast-message.slideIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b81ac806-4838-4300-8e6e-af3ac177f560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-message slideIn</value>
      <webElementGuid>e6595d1d-e890-4577-90eb-de6f74e9f062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address Verification Will Be Completed In 48 Hours</value>
      <webElementGuid>d1f4b58b-eb50-4c82-985f-eec8e7644cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T0tBZGRyZXNzJTIwVmVyaWZpY2F0aW9uJTIwV2lsbCUyMEJlJTIwQ29tcGxldGVkJTIwSW4lMjA0OCUyMEhvdXJzZ3JlZW4&quot;)/div[@class=&quot;iziToast-body&quot;]/div[@class=&quot;iziToast-texts&quot;]/p[@class=&quot;iziToast-message slideIn&quot;]</value>
      <webElementGuid>a03ce1fd-1699-4de4-a3ea-71580f1a63a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='T0tBZGRyZXNzJTIwVmVyaWZpY2F0aW9uJTIwV2lsbCUyMEJlJTIwQ29tcGxldGVkJTIwSW4lMjA0OCUyMEhvdXJzZ3JlZW4']/div/div/p</value>
      <webElementGuid>20a705e6-cd6b-4766-a02f-2537a0ca84d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::p[1]</value>
      <webElementGuid>5e8d02b0-c4da-47bf-83bd-5198ae39053a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::p[1]</value>
      <webElementGuid>00db2006-06c9-4c33-9005-d8df1fc85787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/p</value>
      <webElementGuid>e6c6eb9e-e9c4-44e6-8709-9e8096d402eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Address Verification Will Be Completed In 48 Hours' or . = 'Address Verification Will Be Completed In 48 Hours')]</value>
      <webElementGuid>ff45eb72-70f6-4870-ab84-b85e2af8af42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
