<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_bluintouchapp_1</name>
   <tag></tag>
   <elementGuidId>c576f6f8-8164-4c02-b5a5-4d8af9f06134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs3__option-11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs23__option-11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6460e8a2-2756-4c5e-96a0-171270125b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs23__option-11</value>
      <webElementGuid>73faf3d2-15d2-4b27-8a38-1203085300b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b858643c-bc75-4aaf-8c64-b72d76a9f0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>24d0b013-e1ff-4ed7-9009-56dac26ee3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ecaa128-829c-4de6-ad8f-fcac85fc08d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          bluintouchapp
        </value>
      <webElementGuid>6305183a-bb59-49cc-844c-e38881fd0929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs23__option-11&quot;)</value>
      <webElementGuid>c5648726-f1bf-4dc3-9aef-94c34a83fce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs23__option-11']</value>
      <webElementGuid>d59e4e11-bd47-4959-abee-a010fa320644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs23__listbox']/li[12]</value>
      <webElementGuid>75a3fe23-ff33-47ec-b08d-16537c59c715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='business_verification'])[1]/following::li[1]</value>
      <webElementGuid>216b12e5-fa71-4594-be17-d3a8e2f653f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='olas-app'])[1]/following::li[2]</value>
      <webElementGuid>0ead394a-bc45-4e37-bbff-1b21ec507584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='liveness'])[1]/preceding::li[1]</value>
      <webElementGuid>7e7e7aea-079c-4c33-9770-d475f2127254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test-sms-config'])[1]/preceding::li[2]</value>
      <webElementGuid>1e49f1e5-63ba-4cd4-82c6-bffa77459573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bluintouchapp']/parent::*</value>
      <webElementGuid>ccce26af-e00f-48f5-85d0-05412212f5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]</value>
      <webElementGuid>4a24c8fd-16a6-45d3-8f9d-51de7fe788c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs23__option-11' and (text() = '
          bluintouchapp
        ' or . = '
          bluintouchapp
        ')]</value>
      <webElementGuid>f526217f-f951-43f9-8758-791fa9c57025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
