<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Flat_pointer mr-4</name>
   <tag></tag>
   <elementGuidId>13fc81c5-e4bd-455b-acdf-796368397bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/table/tbody/tr/td[6]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.pointer.mr-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1783c44-ade1-4fef-833a-4fe7a83b2bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/icons/edit.png</value>
      <webElementGuid>421cf9be-0dbb-454f-9e71-6b99f7e038b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>update Coupon</value>
      <webElementGuid>ab890a85-3edc-43ac-af67-737cff8deb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>e4ade286-748c-4ba3-9095-3595c4785267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer mr-4</value>
      <webElementGuid>216131b1-0efb-459e-aee9-f760a620b1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[2]/div[@class=&quot;p-md-4 p-3&quot;]/div[@class=&quot;card pt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;v-table VueTables VueTables--server&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;VueTables__table table table-striped table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;VueTables__row&quot;]/td[6]/div[1]/div[@class=&quot;d-flex&quot;]/div[1]/img[@class=&quot;pointer mr-4&quot;]</value>
      <webElementGuid>5e38957b-cdc9-4f71-aa96-5eeb75e477b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/table/tbody/tr/td[6]/div/div/div/img</value>
      <webElementGuid>bd94747d-b6b9-4a45-852b-7b14de11bb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='update Coupon']</value>
      <webElementGuid>bc522948-d8fc-4b43-9a99-c232b02277c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div/img</value>
      <webElementGuid>0c505337-3bc1-4b1c-a566-8a3f257bebc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/icons/edit.png' and @alt = 'update Coupon']</value>
      <webElementGuid>30cf2817-bda1-47b1-a26c-6bb85ef70a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
