<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Freedom OPlan</name>
   <tag></tag>
   <elementGuidId>b4131bc4-f049-488b-bb9d-589b1a875af0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs39__option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs39__option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c6029533-fc07-4b4b-bf95-c76f7d483582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs39__option-1</value>
      <webElementGuid>c5d11527-6a73-4caa-aec0-5d21d5c9cf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c9fff745-6eaa-4ca2-b2a7-61517bc9802c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>88f75418-d281-4519-9414-bf93d8f02d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce4d218c-86a7-4aa2-94b0-4049c501b028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Freedom OPlan
        </value>
      <webElementGuid>2c0be482-ff23-43a4-90ef-2f40211bb02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs39__option-1&quot;)</value>
      <webElementGuid>78161d9c-c0a6-46e1-ada8-28af985d31dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs39__option-1']</value>
      <webElementGuid>5a54379a-4d67-45e3-8092-4beac8b511f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs39__listbox']/li[2]</value>
      <webElementGuid>fe616520-00f0-42d9-b35a-884657b10b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Plans'])[1]/following::li[1]</value>
      <webElementGuid>09a9f6e0-99f0-4ecf-bde2-18b2cce80581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[3]/following::li[2]</value>
      <webElementGuid>65b5377e-e274-4191-9e10-4d1c29e27565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yanga Plan'])[1]/preceding::li[1]</value>
      <webElementGuid>ad283e03-94d2-4bf9-8376-fea10a025b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST'])[1]/preceding::li[2]</value>
      <webElementGuid>3e2958b3-792d-471e-b35a-bfebcff00645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Freedom OPlan']/parent::*</value>
      <webElementGuid>83f00144-045b-45b2-93bb-4bc8b8a20910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/ul/li[2]</value>
      <webElementGuid>7d6c9ea0-ded5-4605-9f57-ef8a67d41629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs39__option-1' and (text() = '
          Freedom OPlan
        ' or . = '
          Freedom OPlan
        ')]</value>
      <webElementGuid>5b0eaf66-7061-4718-affb-9be3d44a5afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
