<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Clear_ml-3 pointer</name>
   <tag></tag>
   <elementGuidId>326bb898-28bd-46d1-9ed5-422961c245aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sms_logs']/div/div/div/form/div/div[3]/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ml-3.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>93c415cc-3af1-4c15-9287-33b07b62badf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/icons/download.png</value>
      <webElementGuid>7df6557b-74e2-4c74-bc42-0ce6525f743d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Download as csv</value>
      <webElementGuid>b15c4b87-c144-43e1-aade-1f241fd5ff9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30px</value>
      <webElementGuid>09d44c45-a42e-4936-89b1-7d623d9360eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-3 pointer</value>
      <webElementGuid>c993add6-aa7a-4b19-b714-8613725a7a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sms_logs&quot;)/div[@class=&quot;col-12 pt-3&quot;]/div[@class=&quot;px-3&quot;]/div[@class=&quot;filters-wrapper&quot;]/form[@class=&quot;active&quot;]/div[@class=&quot;row mb-2&quot;]/div[3]/div[@class=&quot;d-inline-block&quot;]/span[1]/img[@class=&quot;ml-3 pointer&quot;]</value>
      <webElementGuid>da2df5aa-0507-4030-9fcc-a8f790290d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sms_logs']/div/div/div/form/div/div[3]/div/span/img</value>
      <webElementGuid>4a291127-42d5-4fd0-a809-ccb102e54835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Download as csv']</value>
      <webElementGuid>a20705a7-71fe-4071-b5d8-b79fead81ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>aade996d-57cb-437a-b929-19beed2b0d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/icons/download.png' and @alt = 'Download as csv']</value>
      <webElementGuid>700d9d11-4fae-43a5-8d30-0a38af3c7ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
