<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Phone Number_vti__flag gb</name>
   <tag></tag>
   <elementGuidId>a7f6ef41-6377-485f-b63c-708ce3c83385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='send_single_sms']/form/div/div/div[2]/div/div[2]/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.vti__flag.gb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61b4d2c5-8138-48cc-86f9-dfc06592d624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vti__flag gb</value>
      <webElementGuid>b71a6706-cf0c-466e-8068-8be626a7fff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send_single_sms&quot;)/form[@class=&quot;row border-bottom pb-4 my-4&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-9 col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-wrapper&quot;]/div[@class=&quot;form-control w-100 input-bordered p-0 vue-tel-input&quot;]/div[@class=&quot;vti__dropdown&quot;]/span[@class=&quot;vti__selection&quot;]/span[@class=&quot;vti__flag gb&quot;]</value>
      <webElementGuid>a3d9ba1a-080e-4d0a-869c-1aed4b36f49c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='send_single_sms']/form/div/div/div[2]/div/div[2]/div/div/span/span</value>
      <webElementGuid>a6498bf8-1491-4908-b1b3-691d2a123c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>b874cad0-a5e0-483d-9c22-4f51a1dd0315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
