<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_sms-27e89b65fc049de80cc645290a637e92</name>
   <tag></tag>
   <elementGuidId>32953eba-0a34-496e-8971-0e1ada9a2081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sms_logs']/div/div[2]/div/div/div/div[2]/table/tbody/tr[8]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9a08fbf5-ddfe-49d2-b8c8-1061ea262bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce31d98c-740d-4ba8-a32e-f17d306a0549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sms-27e89b65fc049de80cc645290a637e92</value>
      <webElementGuid>110ecb92-9dd1-40e6-a03f-a0839f0d59c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sms_logs&quot;)/div[@class=&quot;col-12 pt-3&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;v-table VueTables VueTables--server&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;VueTables__table table table-striped table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;VueTables__row&quot;]/td[1]</value>
      <webElementGuid>2a335b22-face-44cd-addf-836f80cbf909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sms_logs']/div/div[2]/div/div/div/div[2]/table/tbody/tr[8]/td</value>
      <webElementGuid>e892b2a4-4b95-4dae-8a12-56af33486876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SENDING'])[7]/following::td[2]</value>
      <webElementGuid>96857c38-6e78-4814-8d82-973a8f901d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blusalt'])[7]/following::td[3]</value>
      <webElementGuid>92692394-0ffc-4324-9b84-304013b99405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blusalt'])[8]/preceding::td[2]</value>
      <webElementGuid>4f5435dd-635f-42ad-8318-8135b5c62485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SENDING'])[8]/preceding::td[3]</value>
      <webElementGuid>1b91a0bf-26c9-418a-9bab-2395f9b62539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sms-27e89b65fc049de80cc645290a637e92']/parent::*</value>
      <webElementGuid>4a28fea8-fed8-4cbf-ac5f-c0fc33194cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td</value>
      <webElementGuid>c0a2eebb-cefc-4745-b08b-55f4450f7039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'sms-27e89b65fc049de80cc645290a637e92' or . = 'sms-27e89b65fc049de80cc645290a637e92')]</value>
      <webElementGuid>1ad4bfe9-9272-40bd-8a49-e6f699705206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
