<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Password_fas fa-eye-slash fs-24</name>
   <tag></tag>
   <elementGuidId>e0a7f31e-0c1a-4380-a47c-9a0a1791540f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.fas.fa-eye-slash.fs-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>1665363d-14ee-4945-9c00-c78fbe2c16a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye-slash fs-24</value>
      <webElementGuid>1e56f8db-846c-4e51-86e5-923b6f8e6e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[1]/div[@class=&quot;w-bg page-ath&quot;]/div[@class=&quot;row justify-content-center align-items-center&quot;]/div[@class=&quot;no-sm-padding col-xl-4 col-lg-5 col-md-4 col-sm-12&quot;]/div[1]/div[@class=&quot;card-innr card-login auth-card&quot;]/form[1]/div[@class=&quot;form-group mg-b-20&quot;]/div[@class=&quot;pos-relative&quot;]/div[@class=&quot;d-flex pos-absolute t-5 mt-2 r-10&quot;]/span[@class=&quot;input-icon input-icon-right&quot;]/em[@class=&quot;fas fa-eye-slash fs-24&quot;]</value>
      <webElementGuid>12635701-791e-4401-b4a4-e49dc54a7b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>3209797c-3b73-4b2a-a8b0-3e3a9c03a6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
