<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>6fb17232-c862-4c14-91a0-5b9d521ee53a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itemPRD-AZPKHGAOH70']/div/div/div[2]/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn--sm.btn--primary.px-5.mx-auto.fw-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0717bace-53ee-4cf1-8036-0ff21746ae48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--sm btn--primary px-5 mx-auto fw-bold</value>
      <webElementGuid>cccac306-86ee-427f-a8cf-547ebf799c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			Done
		</value>
      <webElementGuid>8df3947e-59fd-455c-85c0-e0081253403e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemPRD-AZPKHGAOH70&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn--sm btn--primary px-5 mx-auto fw-bold&quot;]</value>
      <webElementGuid>5ad5e632-90c5-4ece-9726-9dc58b3c0de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemPRD-AZPKHGAOH70']/div/div/div[2]/div/div/button[2]</value>
      <webElementGuid>db3280aa-0846-4394-95c4-7e1811862c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Updated Successfully'])[1]/following::button[2]</value>
      <webElementGuid>4a8887d7-9370-4fce-8f3f-a402311e362d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Yanga plan'])[1]/following::button[3]</value>
      <webElementGuid>24cc107e-c9b8-46bc-af2f-f3e2524a64ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Yanga Plan'])[1]/preceding::button[1]</value>
      <webElementGuid>80f9302e-05eb-4652-ba61-2dfa36e4a839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>77c1def4-fe53-4fa4-a966-f500940cff9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>bbf41296-4209-439f-b6b3-70a7275e9aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
			Done
		' or . = '
			Done
		')]</value>
      <webElementGuid>5ba4004e-123b-4430-bf9f-bbce6d51aef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
