<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Identity(Ghana)</name>
   <tag></tag>
   <elementGuidId>88457ebd-2aeb-455f-9d15-4bfa245e0e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headingFive > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headingFive']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f0e2408-7d2a-460b-bc3c-1ad035470bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>e72bdab6-ee17-4d93-b0fc-b9488bc8010c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseFive</value>
      <webElementGuid>f2b893db-0726-4635-9caf-fbe0ecf963d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseFive</value>
      <webElementGuid>146afb19-b3fd-4481-9847-4864547cc82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identity(Ghana)</value>
      <webElementGuid>2475689f-a3cb-4af4-bf05-617db209085b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingFive&quot;)/a[1]</value>
      <webElementGuid>c891efc8-274b-4a83-9378-8d45c0fe63bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headingFive']/a</value>
      <webElementGuid>cbdf4868-c7e1-4d14-9a20-4caa527fe0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Verification'])[1]/following::a[1]</value>
      <webElementGuid>7eb47623-73a2-4451-b302-20436d24e8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers Licence (DL)'])[1]/following::a[2]</value>
      <webElementGuid>1d14af78-6f11-45e3-a500-7bac20d2d6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voters ID Card (GVC)'])[1]/preceding::a[1]</value>
      <webElementGuid>72fb2357-a63e-40eb-a5c2-91da6501e0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseFive')]</value>
      <webElementGuid>fce68fa0-9d9c-4288-ae2f-6c28947f8d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>8bab3583-5271-452a-a1e3-fde336e3cf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#collapseFive' and (text() = 'Identity(Ghana)' or . = 'Identity(Ghana)')]</value>
      <webElementGuid>09b3ed94-8943-4ed0-95e9-0329451646f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
