<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Identity(Nigeria)</name>
   <tag></tag>
   <elementGuidId>10868368-56f9-48e4-a562-b3ddd2eedb24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headingOne > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headingOne']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2fd3a3df-a57e-4bf4-93ea-e3f845f6f203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>4776b43f-c882-4353-a639-1f956ba59df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseOne</value>
      <webElementGuid>2eb54e5f-c3a8-4642-a7af-6b32b8d4a504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64dde7ca-d69e-474b-a9cb-e105918d1c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseOne</value>
      <webElementGuid>4b9b06af-13b8-4034-85fd-c11d613d12ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identity(Nigeria)</value>
      <webElementGuid>c7d35dae-3733-4b8f-9f6f-915b5515c493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingOne&quot;)/a[1]</value>
      <webElementGuid>faf2561a-d159-42fd-937b-90f80959fc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headingOne']/a</value>
      <webElementGuid>2713fc5d-1c40-4a7d-a1a1-38dbe61a6eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::a[2]</value>
      <webElementGuid>d58d269a-14fc-4bf6-854f-7dd7e88dd196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='farida@blusalt.net'])[1]/following::a[3]</value>
      <webElementGuid>5340e7df-82a8-4145-9bda-d9b31ba91096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Verification Number (BVN)'])[1]/preceding::a[1]</value>
      <webElementGuid>efc2a46b-b6b9-478b-a2d9-b27e613b5234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseOne')]</value>
      <webElementGuid>905f7965-1811-46cc-97f6-b75abd139f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>366ae3eb-e7d9-4b31-8fd7-e411271dd937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#collapseOne' and (text() = 'Identity(Nigeria)' or . = 'Identity(Nigeria)')]</value>
      <webElementGuid>e53c84d3-c793-41b4-9d4f-a6df17577193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
