<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__vs__selected-options_1</name>
   <tag></tag>
   <elementGuidId>9af3aaff-5cb0-48fe-a9e4-69f9b3bc36de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs5__combobox > div.vs__selected-options</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs5__combobox']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60c528e8-3471-4b07-9f8c-e4487a7a30bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__selected-options</value>
      <webElementGuid>7dae4057-ba63-45c0-873d-31b8755f807a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs5__combobox&quot;)/div[@class=&quot;vs__selected-options&quot;]</value>
      <webElementGuid>eca9f74b-2d4e-41b2-9e46-4948e372af0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs5__combobox']/div</value>
      <webElementGuid>adba31f5-e65b-4907-9dbd-a54e92e78155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[3]</value>
      <webElementGuid>0d7d5e26-d4ef-47e8-b894-f1c25c5c201f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/preceding::div[1]</value>
      <webElementGuid>7f29c3d5-aaee-4bfa-8f7d-28c77e5ee2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1'])[1]/preceding::div[3]</value>
      <webElementGuid>4b9d53f7-ccdb-43aa-9bf1-27fb37822eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>cee0522e-e638-4916-a1d1-d0d9cda3b231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
