<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Ghana Drivers Licence Response</name>
   <tag></tag>
   <elementGuidId>4a6122ab-ce7b-4ae5-8510-1ba09687b364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5ef09da8-1801-4073-b683-ff14cd430313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ghana Drivers Licence Response</value>
      <webElementGuid>8c786a86-c026-4e48-87f8-f2289f1794aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;az-content-box&quot;]/div[@class=&quot;az-content-body tab-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;user-settings-section&quot;]/div[@class=&quot;user-settings-section-header&quot;]/div[@class=&quot;user-settings-section-header-text&quot;]/h1[1]</value>
      <webElementGuid>9f17b00d-2f35-4679-acd7-3aa06d86f528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div/div/h1</value>
      <webElementGuid>bd876dd5-adaa-46c2-a1f1-cb2c1dc23f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National ID'])[1]/following::h1[1]</value>
      <webElementGuid>91bbecdd-44d4-4a96-8ebc-158ea22a7e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International Passport (KIP)'])[1]/following::h1[1]</value>
      <webElementGuid>50388b1a-ad10-4681-beee-f4258678ab8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::h1[1]</value>
      <webElementGuid>385c3c30-bfe2-4e9c-b23f-4cbbfdb0a3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ghana Drivers Licence Response']/parent::*</value>
      <webElementGuid>174bacce-06dc-4080-b706-11a8a056b77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>9d82e97c-a022-4d07-a275-c804cd819b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Ghana Drivers Licence Response' or . = 'Ghana Drivers Licence Response')]</value>
      <webElementGuid>5dd855c5-c4b9-4e50-b9fa-e410c3837d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
