<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_identity-test</name>
   <tag></tag>
   <elementGuidId>9b01a364-d50b-45ed-8239-048af683ff18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'option-0') and (contains(text(), 'identity-test
        ') or contains(., 'identity-test
        '))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs4__option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs4__option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2a930a84-5758-4c4d-b35e-37bf0d6e7a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>e58ff00c-4e85-4b8b-8bd6-1e6baa245de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>293d5920-c4dc-42f5-bd15-5a25d78b7481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>f66fc956-2846-4035-94c2-dd8e09fa20fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9aefa677-0666-4412-89d5-4588725fb58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>identity-test
        </value>
      <webElementGuid>2362c5e5-9f9a-490e-bd1c-48d68c9041a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__option-0&quot;)</value>
      <webElementGuid>a0e9074e-d72e-4aa1-b1ba-6fce8568ae89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs4__option-0']</value>
      <webElementGuid>3032f236-2382-44b3-bffc-46b998d050f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs4__listbox']/li</value>
      <webElementGuid>3d0efc15-000f-46aa-bf9e-6a0490164dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[1]</value>
      <webElementGuid>64e54cf2-58a7-4eb6-bd34-b8e836834eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::li[1]</value>
      <webElementGuid>ef669c0d-c83a-499b-9130-169cc3d46f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='infohob-identity'])[1]/preceding::li[1]</value>
      <webElementGuid>5a5b23bb-f4a9-4066-9e1a-e726d1c2d847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bvn-verification'])[1]/preceding::li[2]</value>
      <webElementGuid>b82a07b2-aede-472d-909d-270f2a83a082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='identity-test']/parent::*</value>
      <webElementGuid>ebb5d087-4201-4c27-8e51-8bddd45f4e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li</value>
      <webElementGuid>99a52426-afee-4f54-913f-3c3400c802f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs4__option-0' and (text() = '
          identity-test
        ' or . = '
          identity-test
        ')]</value>
      <webElementGuid>0edc02a8-d769-407b-89b3-0a9c11b4e5db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
