<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your file is Successfully Uploaded</name>
   <tag></tag>
   <elementGuidId>df6b48c3-5445-4b6f-8165-6fa2f538e95f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T0tZb3VyJTIwZmlsZSUyMGlzJTIwU3VjY2Vzc2Z1bGx5JTIwVXBsb2FkZWRncmVlbg']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.iziToast-message.slideIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8653e01d-c24c-495b-b499-35c03c05b4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-message slideIn</value>
      <webElementGuid>1a0b4804-e8d3-40df-94ce-0b623f146439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your file is Successfully Uploaded</value>
      <webElementGuid>81ac96d3-0df8-48a6-8b6e-528a002f2aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T0tZb3VyJTIwZmlsZSUyMGlzJTIwU3VjY2Vzc2Z1bGx5JTIwVXBsb2FkZWRncmVlbg&quot;)/div[@class=&quot;iziToast-body&quot;]/div[@class=&quot;iziToast-texts&quot;]/p[@class=&quot;iziToast-message slideIn&quot;]</value>
      <webElementGuid>8d12172e-d50b-490e-8ebe-6a58d578a1d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='T0tZb3VyJTIwZmlsZSUyMGlzJTIwU3VjY2Vzc2Z1bGx5JTIwVXBsb2FkZWRncmVlbg']/div/div/p</value>
      <webElementGuid>136fad69-94b2-4fed-b5ad-6c9930b0b17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::p[1]</value>
      <webElementGuid>deff411c-465f-4f8b-ad4f-4788626166e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 BluSalt'])[1]/following::p[1]</value>
      <webElementGuid>0fabfa45-d399-4819-945b-ec4b91c43fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your file is Successfully Uploaded']/parent::*</value>
      <webElementGuid>650b2430-495e-4ddf-bfe6-77d187a73912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/p</value>
      <webElementGuid>4032579b-caa7-477f-b91c-599d048d88ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your file is Successfully Uploaded' or . = 'Your file is Successfully Uploaded')]</value>
      <webElementGuid>898c9705-1c51-4868-b81c-2d375c854670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
