<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Currency Type_vs__selected-options_1</name>
   <tag></tag>
   <elementGuidId>06f3a835-7d5c-4fb6-8014-61a16d434235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs3__combobox']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs12__combobox > div.vs__selected-options</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;vs12__combobox&quot;)/div[@class=&quot;vs__selected-options&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4d6a8b5-ad92-47c6-b966-4120cd60b691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__selected-options</value>
      <webElementGuid>e1d79c49-3dba-4379-9174-b86de9497477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs12__combobox&quot;)/div[@class=&quot;vs__selected-options&quot;]</value>
      <webElementGuid>72a167a5-dc6f-49b6-a833-a5474059b440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs12__combobox']/div</value>
      <webElementGuid>f47f926c-9adc-4817-87d0-fac6441c3145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency Type'])[1]/following::div[3]</value>
      <webElementGuid>69375d97-4a3d-4549-9d98-40cefb5ce2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API version field is required.'])[1]/following::div[4]</value>
      <webElementGuid>2dcfe28b-e5db-4e4b-af9c-a7250024fe6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[3]/preceding::div[1]</value>
      <webElementGuid>de7ab32d-bb22-486a-b5a3-95ca5baac65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NGN'])[1]/preceding::div[3]</value>
      <webElementGuid>edd60c15-ba90-4332-a312-a25ad0596488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>520ec1a0-dea5-4127-b81c-2937cb1b18ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
