<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Customer Address Updated Successfully</name>
   <tag></tag>
   <elementGuidId>0c4a8763-8b2e-4459-8ca8-532a16c216ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TCU-49AU9CRVIPGG9']/div/div/div[2]/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.py-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>dbeee70b-2597-47f6-bb58-6f3f2b165e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-3</value>
      <webElementGuid>2a3e3833-4964-449a-bf09-f348bc6baf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Address Updated Successfully</value>
      <webElementGuid>fee7fe32-8e64-4d99-8773-fa02f8afa2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TCU-49AU9CRVIPGG9&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;text-center&quot;]/h5[@class=&quot;py-3&quot;]</value>
      <webElementGuid>3ef4891a-b97d-4226-bdcc-5d7079b03bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TCU-49AU9CRVIPGG9']/div/div/div[2]/div/div/h5</value>
      <webElementGuid>9f4ee6f5-ce8c-42bf-aa7f-93f138c5bbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Customer Address'])[1]/following::h5[1]</value>
      <webElementGuid>bc106ca8-734b-41f6-8036-1dca091a4dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Address'])[1]/following::h5[1]</value>
      <webElementGuid>5689ab3b-dfc7-455e-9cc1-7d48a059fa47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::h5[1]</value>
      <webElementGuid>089310e7-58b4-4faa-9ec7-99e9f4dd0e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency'])[1]/preceding::h5[1]</value>
      <webElementGuid>83507887-75dd-49b0-8d71-c446e1f72b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Address Updated Successfully']/parent::*</value>
      <webElementGuid>008b6a12-6a74-4fa8-bfc5-f4992a56623b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>6bdfbf4d-eec4-4bc1-a896-d5008d965db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Customer Address Updated Successfully' or . = 'Customer Address Updated Successfully')]</value>
      <webElementGuid>f042537b-bd59-4072-81e1-656369ad2f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
