<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_NGN</name>
   <tag></tag>
   <elementGuidId>2a00f772-fef6-4bf0-8d63-3629d8970f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'option-0')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs6__option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs6__option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2c8c8840-5c01-4fe5-8265-ed3805554d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>c15f99d2-f1ab-4d66-b434-847303aeae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1bdfa33f-4362-46c8-b758-48b81cbfe3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>ba8cd977-5e46-4c4d-8126-5dc87a6f82f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b35c0024-8c80-4bc7-888f-0a04008f1e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          NGN
        </value>
      <webElementGuid>4d6e39fa-ee36-450c-8ce6-4d5c0190de7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs6__option-0&quot;)</value>
      <webElementGuid>e8aec93d-a886-4b9e-a0ca-b3fc9b71c05d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs6__option-0']</value>
      <webElementGuid>5f8775d8-59bb-4e65-a25e-73b844e1d56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs6__listbox']/li</value>
      <webElementGuid>03a6ecde-dadb-42cc-88ae-9e7dec8cbe96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[3]/following::li[1]</value>
      <webElementGuid>f97d76b9-c2ab-458e-8863-47b8904719c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency Type'])[1]/following::li[1]</value>
      <webElementGuid>40b28b55-c60c-4c90-9fb6-20791a5171c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::li[1]</value>
      <webElementGuid>ca141c65-350e-4c3b-8289-4317ac64f921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Request Format'])[1]/preceding::li[1]</value>
      <webElementGuid>be90ed12-e250-4fbc-903a-a93c4a240c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NGN']/parent::*</value>
      <webElementGuid>a370aa36-bc90-45ce-a868-e81086b8dd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li</value>
      <webElementGuid>bcb3694c-5fbe-4f55-8a1f-ddd9336779ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs6__option-0' and (text() = '
          NGN
        ' or . = '
          NGN
        ')]</value>
      <webElementGuid>fa70808c-9236-4a2d-b186-82892e8e09e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
