<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Error_iziToast-close</name>
   <tag></tag>
   <elementGuidId>b76e7fbd-929e-443d-9f55-89f6bb39a787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.iziToast-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00b4a658-a5d8-4a16-b409-e7aad5a5cd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0199de6-ef6f-47b7-8802-073e2fae8540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-close</value>
      <webElementGuid>53834d25-42aa-4f5a-8178-a240f1a6aa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RXJyb3JGaXJzdCUyMG5hbWUlMjBpcyUyMHJlcXVpcmVkcmVk&quot;)/button[@class=&quot;iziToast-close&quot;]</value>
      <webElementGuid>ecdf53a2-d732-4c3a-978a-c4060ef59a28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>38b740e6-1dba-49d3-9b16-e589db39c9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RXJyb3JGaXJzdCUyMG5hbWUlMjBpcyUyMHJlcXVpcmVkcmVk']/button</value>
      <webElementGuid>275fc067-d979-4bdc-9d42-3d4c4e843be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>0d8e8fef-b7a0-43a1-a2ad-b716dd7c7b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>4ad6883f-7c14-4ae9-b997-b5c93049d2b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
