<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_NGN</name>
   <tag></tag>
   <elementGuidId>9ec84311-cf6d-404c-9282-7869e4a3082b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs5__option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs5__option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b4f96f9d-ecc1-4407-b24f-624813a59f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs5__option-0</value>
      <webElementGuid>0c8e9d3f-18eb-4dc0-b9da-81e5b9330c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>975d40aa-d6f9-41b2-8d3f-130b052bf9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>8a261d7d-9592-4922-9b66-417e045decd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e2e1422-e50c-4626-bbf1-69d3a3032505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          NGN
        </value>
      <webElementGuid>cdb81c21-5a76-402b-ab7c-3fff52263dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs5__option-0&quot;)</value>
      <webElementGuid>dcbef53d-ee61-4ca0-84a4-d7b72186b733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs5__option-0']</value>
      <webElementGuid>a969c86c-8a0d-4d30-80fa-08e8390137d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs5__listbox']/li</value>
      <webElementGuid>f12e688e-3655-4a41-b721-96b8f6036123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::li[1]</value>
      <webElementGuid>b3a4fd10-d817-42b8-9b6b-4ed455c0c5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency Type'])[1]/following::li[1]</value>
      <webElementGuid>0ba2128c-34a5-49c9-8705-b4c447c37640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify vNIN'])[1]/preceding::li[1]</value>
      <webElementGuid>ea5aed47-b505-4daa-b7d8-6af1f46d7d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Request Format'])[1]/preceding::li[1]</value>
      <webElementGuid>3d052713-4db7-45c4-868d-2d5a8411c84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NGN']/parent::*</value>
      <webElementGuid>ccd930a7-3155-4b0a-9d3a-e3dc1fdec330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li</value>
      <webElementGuid>7e82abdd-4656-4092-a295-4b9778d30ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs5__option-0' and (text() = '
          NGN
        ' or . = '
          NGN
        ')]</value>
      <webElementGuid>7895f9e5-4541-4b5e-99e6-f688fa2a905f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
