<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>08d81b86-c446-438d-9d60-7feb33d56c49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div/div/div[2]/div[2]/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn--lg.btn--primary.g-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b8223ec-8d7f-4a5f-b2b5-7d157680bd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary g-bold</value>
      <webElementGuid>9cac3459-67f5-4222-96ed-d4593187dc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>f2c98cd0-fec0-4701-969b-1fb7d851bb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sc-gsnTZi cKWxtb checkout&quot;]/div[@class=&quot;checkout__container&quot;]/div[@class=&quot;checkout__main&quot;]/div[@class=&quot;checkout__content&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;g-bold text--gray&quot;]/div[@class=&quot;col-xl-6 col-8 mx-auto&quot;]/button[@class=&quot;btn btn--lg btn--primary g-bold&quot;]</value>
      <webElementGuid>4d9244a6-9818-4327-94bd-530e77db2b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Blusalt - An overview of all your wallets/iframe_Dashboard_frame</value>
      <webElementGuid>f3065484-39b6-47d2-a935-f6e4e0d6f0f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div/div/div[2]/div[2]/div/div[3]/button</value>
      <webElementGuid>a006b34c-1c7f-4a93-994e-06e18e8aa06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::button[1]</value>
      <webElementGuid>5d84eefb-143a-4264-bd5e-e8e0fb1cc487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blusalt'])[1]/preceding::button[1]</value>
      <webElementGuid>0cfcb156-94ad-4f1b-a58e-aad52ea5579d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back']/parent::*</value>
      <webElementGuid>70980c2e-5de1-409f-90bf-ab54abc724bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>777ad933-d294-4157-87c5-6c627a680636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>9ce1ec1b-6b8b-4ce3-a725-9c39693755f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
