<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_N7100  1Month</name>
   <tag></tag>
   <elementGuidId>1942f8c2-6f39-4c61-9166-7319665c5b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs24__option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs24__option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3b0ffbaa-3afe-4090-bdef-13a92a82aeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs24__option-0</value>
      <webElementGuid>2038363d-ecd2-4d95-8c0c-abf96c5f38dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4a077f70-b9a0-4154-ab3f-6ed09220e306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>6377d3f9-b5c3-4b0b-8a57-33e7ea3e4858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07d5873a-56eb-4fd1-be6d-18774b967db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          N7100 | 1Month
        </value>
      <webElementGuid>642b2f71-99ce-40c4-9faa-05ebaa8394b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs24__option-0&quot;)</value>
      <webElementGuid>0cc71de0-ce7e-495d-b350-f9a0d0d21a70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs24__option-0']</value>
      <webElementGuid>6b6f0954-3455-4a93-8930-191a997ccb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs24__listbox']/li</value>
      <webElementGuid>445428b1-2f8b-44fc-b0c9-5619a1d34a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[5]/following::li[1]</value>
      <webElementGuid>27a77263-6896-4dd5-bee8-2ec0a20da003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N14200 | 2Months'])[1]/following::li[1]</value>
      <webElementGuid>f7fe0e9d-ad21-421c-aeb4-dde9d67d6637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N14200 | 2Months'])[2]/preceding::li[1]</value>
      <webElementGuid>c9a88e28-8e4c-416c-bd35-e4351e1ccba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N21300 | 3Months'])[1]/preceding::li[2]</value>
      <webElementGuid>efcb2aca-075e-469c-8f9e-0f17ea35fad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='N7100 | 1Month']/parent::*</value>
      <webElementGuid>81b59389-25e2-4d75-aa41-24fb884b2b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li</value>
      <webElementGuid>1dc28064-e2c4-49b0-ae78-d1fc457da2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs24__option-0' and (text() = '
          N7100 | 1Month
        ' or . = '
          N7100 | 1Month
        ')]</value>
      <webElementGuid>0ec1acb2-75a4-4f28-bfcd-e2e64a583680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
