<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Port-Harcourt Disco</name>
   <tag></tag>
   <elementGuidId>c8c87234-8c9f-4b3a-926b-3c020290f213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs22__option-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs22__option-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>09a81290-93f0-40e0-94e8-e97b98ca3fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs22__option-8</value>
      <webElementGuid>1190009a-1ccc-466a-846a-af5356a6422a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c36dc7d7-26fe-4f2e-9b7d-9e65d3623a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>1e78df88-dfb7-4c4f-9b37-5b5899f9bd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c21f240-1165-4b23-870d-8ed7b1991288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Port-Harcourt Disco
        </value>
      <webElementGuid>f4001861-318f-4492-ada0-41e4395ff46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs22__option-8&quot;)</value>
      <webElementGuid>86521533-2a34-486c-9f7a-47a745ec6334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs22__option-8']</value>
      <webElementGuid>800c0753-9efa-45c9-98b9-d3845be8a484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs22__listbox']/li[9]</value>
      <webElementGuid>8a25de61-f039-482f-9605-45077d9c9576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kano Disco'])[1]/following::li[1]</value>
      <webElementGuid>8b848471-1d45-4583-b07d-eff358637597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaduna Disco'])[1]/following::li[2]</value>
      <webElementGuid>74b3e855-8be1-4aa5-9fb2-f1070f8b2e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 BluSalt'])[1]/preceding::li[1]</value>
      <webElementGuid>a7400fff-7c98-4235-9383-6b37df5d92a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'vs22__option-8', '&quot;', ')')])[1]/preceding::li[1]</value>
      <webElementGuid>23592514-9a6d-4465-9272-a73dd997a50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Port-Harcourt Disco']/parent::*</value>
      <webElementGuid>fc62d3ce-c737-46d9-95f9-799c6fd69207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[9]</value>
      <webElementGuid>79bf96d2-4ab1-48af-b637-92969f17ab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs22__option-8' and (text() = '
          Port-Harcourt Disco
        ' or . = '
          Port-Harcourt Disco
        ')]</value>
      <webElementGuid>5b241032-b50a-4a73-983e-83ce0006c3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
