<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_prepaid_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>4afe0bcb-254b-41e4-b098-0b5841c8a2c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs41__option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs41__option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5b2c3501-f945-4793-b799-d0f1c2b2cd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs41__option-0</value>
      <webElementGuid>cd92f963-e4f2-44c2-a055-3a699a6eeaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>68e00ab8-57b5-4593-8e6a-865505fbc6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>af68abc2-1baf-4a28-b7ec-3495b15073ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e614b269-71af-49bd-86cc-34b63bddbe9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          prepaid
        </value>
      <webElementGuid>8552d992-c79a-4d4a-bf61-1ce8d89c1b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs41__option-0&quot;)</value>
      <webElementGuid>5362745a-5527-46b0-89ad-4de45ec68eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs41__option-0']</value>
      <webElementGuid>9000ce89-d9db-46c2-8492-06683538cbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs41__listbox']/li</value>
      <webElementGuid>e7f95403-1a9e-4794-9ea6-31aa5ebea0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[4]/following::li[1]</value>
      <webElementGuid>dc38479a-bcaa-45eb-9da5-f29ac3add04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::li[1]</value>
      <webElementGuid>428f23d8-f391-4c81-97ee-9d0031afa6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='postpaid'])[1]/preceding::li[1]</value>
      <webElementGuid>91aa9596-cf78-40ef-a946-b79e6f10ef54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer/Meter Number'])[1]/preceding::li[2]</value>
      <webElementGuid>0e83dbc0-2222-4c61-8808-5309809865d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='prepaid']/parent::*</value>
      <webElementGuid>36e0e6f9-63b8-4b52-9f2f-5aaa00555673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li</value>
      <webElementGuid>82ea9722-1bae-4c58-be6c-624dfd1d3b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs41__option-0' and (text() = '
          prepaid
        ' or . = '
          prepaid
        ')]</value>
      <webElementGuid>a5ae9766-47ad-42b1-b118-4d308f71a706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
