<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_SML-1GB-300 - 300  1DAY</name>
   <tag></tag>
   <elementGuidId>5b8ee555-49b8-4416-be86-772da3c6ea64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs30__option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs30__option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>14c6959f-22d3-43de-ab3d-b88baaf76398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs30__option-0</value>
      <webElementGuid>2d8af0de-cd32-4b69-a5a6-a61d5587f58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>678971d6-39c8-4050-b67b-ebcecb320d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>c0b7841e-5ed8-431b-8f54-21c761e0f3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>932cdc36-e5dc-437a-b843-5826b4abfae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          SML-1GB-300 - 300 | 1DAY
        </value>
      <webElementGuid>37b73098-2d05-4ccd-a74e-36b7924e1c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs30__option-0&quot;)</value>
      <webElementGuid>8ac0150d-1736-41c3-8776-6779a780611b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs30__option-0']</value>
      <webElementGuid>45f7b7a8-e0e5-4d72-a66c-171a09884141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs30__listbox']/li</value>
      <webElementGuid>b72b1f70-e67b-4f86-a3b8-eb4cf74e7c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[4]/following::li[1]</value>
      <webElementGuid>2c2b5e74-6897-420a-be99-1940a2d370e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::li[1]</value>
      <webElementGuid>81b35a45-4c66-49ab-a556-0c53d134006d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SML-2.5GB-500 - 500 | 1DAY'])[1]/preceding::li[1]</value>
      <webElementGuid>0bd3b13c-6839-4309-b56c-f6196bbcd229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SML-1GB-500 - 500 | 1WEEK'])[1]/preceding::li[2]</value>
      <webElementGuid>3010d056-2c7f-4fcd-8108-ac59721ac0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SML-1GB-300 - 300 | 1DAY']/parent::*</value>
      <webElementGuid>316a53f2-047c-4361-abd4-edd6028d6cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li</value>
      <webElementGuid>2c2c50ac-4b41-4996-a71e-f688966e13d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs30__option-0' and (text() = '
          SML-1GB-300 - 300 | 1DAY
        ' or . = '
          SML-1GB-300 - 300 | 1DAY
        ')]</value>
      <webElementGuid>058170a9-545d-4c2d-bbe6-66e7bc5cc7f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
