<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Data top up successful</name>
   <tag></tag>
   <elementGuidId>65ac8259-c835-46b4-91a7-b8f85330d701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T0tEYXRhJTIwdG9wJTIwdXAlMjBzdWNjZXNzZnVsZ3JlZW4']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.iziToast-message.slideIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3d579f56-c8ba-4ada-88a5-31099b34c6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-message slideIn</value>
      <webElementGuid>b8a71392-74e2-4030-bb56-297fe48073e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data top up successful</value>
      <webElementGuid>85f3ab5f-7921-40e8-97b8-ea15b96628f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T0tEYXRhJTIwdG9wJTIwdXAlMjBzdWNjZXNzZnVsZ3JlZW4&quot;)/div[@class=&quot;iziToast-body&quot;]/div[@class=&quot;iziToast-texts&quot;]/p[@class=&quot;iziToast-message slideIn&quot;]</value>
      <webElementGuid>0487814c-4d25-443c-82c3-e6f9dc942e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='T0tEYXRhJTIwdG9wJTIwdXAlMjBzdWNjZXNzZnVsZ3JlZW4']/div/div/p</value>
      <webElementGuid>1e197487-c1e4-4344-aaa3-7be850cba880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::p[1]</value>
      <webElementGuid>569891f9-7acf-494a-9361-be61b583d3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 BluSalt'])[1]/following::p[1]</value>
      <webElementGuid>ded03e70-398a-4c3e-922b-e3c207ac6c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/p</value>
      <webElementGuid>7d3b0f87-ed26-4c7c-b4b8-88e68ee1f394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Data top up successful' or . = 'Data top up successful')]</value>
      <webElementGuid>87bcac38-ffd5-4c4d-824e-24b7a30c81a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
