<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_successfully fetched dataPlans</name>
   <tag></tag>
   <elementGuidId>8990f921-5b78-419f-a4c3-e454c5fab39d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T0tzdWNjZXNzZnVsbHklMjBmZXRjaGVkJTIwZGF0YVBsYW5zZ3JlZW4']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.iziToast-message.slideIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9d22c9b4-6209-4b92-b696-c155d5394b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-message slideIn</value>
      <webElementGuid>a08685f2-a327-4cc9-8e3b-29d5b19e1320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>successfully fetched dataPlans</value>
      <webElementGuid>e1f2c885-eade-41b9-b1e6-a81f6b8c4303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T0tzdWNjZXNzZnVsbHklMjBmZXRjaGVkJTIwZGF0YVBsYW5zZ3JlZW4&quot;)/div[@class=&quot;iziToast-body&quot;]/div[@class=&quot;iziToast-texts&quot;]/p[@class=&quot;iziToast-message slideIn&quot;]</value>
      <webElementGuid>18f94745-cac8-40c8-a087-83141ef44994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='T0tzdWNjZXNzZnVsbHklMjBmZXRjaGVkJTIwZGF0YVBsYW5zZ3JlZW4']/div/div/p</value>
      <webElementGuid>4b8ebc92-26a4-416b-91bf-4ec8be455498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::p[1]</value>
      <webElementGuid>83695657-48c2-42d4-8e28-0d49ef15fd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'vs16__combobox', '&quot;', ')')])[1]/following::p[1]</value>
      <webElementGuid>bdb49732-f866-46bd-b376-c5fa5b44cba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='successfully fetched dataPlans']/parent::*</value>
      <webElementGuid>46ba41c2-33e8-4b1b-8b66-2c7ede73ee95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/p</value>
      <webElementGuid>48185b09-1d1e-472f-b834-656eea8246f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'successfully fetched dataPlans' or . = 'successfully fetched dataPlans')]</value>
      <webElementGuid>2de049ff-81a2-4f89-b45f-1521d2c4c50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
