<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Phone Number_vti__flag ng_1_2</name>
   <tag></tag>
   <elementGuidId>0fe8342d-bf84-4f0a-9952-dec5f57000e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div[2]/div/div/div[2]/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.vti__flag.ng</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb35e211-f88c-4ae0-99cd-7b1adce710c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vti__flag ng</value>
      <webElementGuid>8b16dbfd-0059-47f4-823b-6e041430e189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;az-content-box&quot;]/div[@class=&quot;az-content-body tab-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[1]/div[@class=&quot;contact-details--card&quot;]/form[1]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-12 col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-wrapper&quot;]/div[@class=&quot;form-control w-100 input-bordered p-0 vue-tel-input&quot;]/div[@class=&quot;vti__dropdown&quot;]/span[@class=&quot;vti__selection&quot;]/span[@class=&quot;vti__flag ng&quot;]</value>
      <webElementGuid>7e892291-0e12-4e06-9815-a02ee906963c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div[2]/div/div/div[2]/div/div/span/span</value>
      <webElementGuid>4f037fec-acda-4428-9f71-ebdeb0027d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>a6d95c0c-0d01-4edd-b363-2f273b09f969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
