<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Credit Remaining_az-profile-link</name>
   <tag></tag>
   <elementGuidId>5eec6b99-63d2-4373-a885-4ea50b5ae208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userProfile']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.az-profile-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23e95847-d97e-485c-b4e8-68b3784db1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>az-profile-link</value>
      <webElementGuid>c6bce13c-5d0f-4e9d-9b8c-fe0f1618850a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userProfile&quot;)/a[@class=&quot;az-profile-link&quot;]</value>
      <webElementGuid>d3b8ac81-4ae8-4630-9e54-05f234baa0ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userProfile']/a</value>
      <webElementGuid>266bfcf1-5bb7-46fc-8713-c2b6ef3f7cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Remaining'])[1]/following::a[1]</value>
      <webElementGuid>3f083030-1b4f-48b9-9d8c-b197452361e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Take A Tour'])[1]/following::a[2]</value>
      <webElementGuid>c684cf4f-459a-4a0d-b3ec-6026bf5b1c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='farida@blusalt.net'])[1]/preceding::a[2]</value>
      <webElementGuid>bf01f698-8091-43df-ab45-17ac4f5fecd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[40]</value>
      <webElementGuid>cbf6ae5e-25e9-4cc0-8c81-f653346af74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>4918e6ec-111e-4c45-b311-cec61709016e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
