<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Duplicate</name>
   <tag></tag>
   <elementGuidId>f6fd0ed3-e226-48c1-b5b6-829bfd05bf5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/table/tbody/tr/td[8]/div/div/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9adf336c-66c8-44aa-b7cb-bef65b718083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>d79be596-556a-4903-8f9c-11548ad5075e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Duplicate
				</value>
      <webElementGuid>3b87dfca-2f3a-4a5e-949a-c2b7a5393509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;p-md-4 p-3&quot;]/div[@class=&quot;pt-3&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;v-table row-pointer VueTables VueTables--server&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;VueTables__table table table-striped table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;VueTables__row&quot;]/td[8]/div[@class=&quot;mr-3&quot;]/div[@class=&quot;dropdown az-profile-menu show&quot;]/div[@class=&quot;dropdown-menu show&quot;]/div[2]/span[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>901b2378-f65a-496f-8573-e68b9b65b403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/table/tbody/tr/td[8]/div/div/div/div[2]/span</value>
      <webElementGuid>9a99ca18-66b8-4e5f-9955-bafa9715ad37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::span[1]</value>
      <webElementGuid>f3691b08-4d26-47bf-bb58-063d7fe9a05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::span[2]</value>
      <webElementGuid>098956f1-a786-4142-acc1-4f8b1bf5eb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue'])[1]/preceding::span[1]</value>
      <webElementGuid>030a2082-9e8c-412a-9020-7f21be770525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[2]</value>
      <webElementGuid>560c8a37-3db6-4997-966c-279b049e5059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Duplicate']/parent::*</value>
      <webElementGuid>13051cdd-c0ef-4815-a403-51fb96860b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/div/div[2]/span</value>
      <webElementGuid>78d71f05-e314-4634-9261-a5311f05827f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
					Duplicate
				' or . = '
					Duplicate
				')]</value>
      <webElementGuid>cb5bf73c-1866-4fb1-ba3f-5608c105064c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
