<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiry Date_expiryDate</name>
   <tag></tag>
   <elementGuidId>000ce901-a832-4caa-bebd-f756d2ce610d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='expiryDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;expiryDate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd452ab7-bb7d-4f30-b829-8fc966d9347a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd673dbc-7fea-4658-8601-6476fdeb7d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiryDate</value>
      <webElementGuid>1e1503ce-825c-44b4-923c-0bb6b30575b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YYYY</value>
      <webElementGuid>26b12030-4b2a-4f74-abb8-9dae15f31467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>75fa0495-ca4a-4141-b778-9d76132de9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d\d/\d\d\d\d</value>
      <webElementGuid>ca57c25c-74a4-46d5-9ed5-b1e06cd6248f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>b34cf995-ad6a-4cb9-bf26-9a89ebda7c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d615232-1bf8-472e-970c-7234808df7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sc-gsnTZi cKWxtb checkout&quot;]/div[@class=&quot;checkout__container&quot;]/div[@class=&quot;checkout__main&quot;]/div[@class=&quot;checkout__content&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;pt-4&quot;]/form[@class=&quot;row pt-4&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group undefined&quot;]/div[@class=&quot;input-wrapper d-flex align-items-center&quot;]/input[1]</value>
      <webElementGuid>71e7c75e-dae8-452b-b873-2125a9fc61bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AccountWallet_OR/Page_Blusalt - Account Wallet/iframe_Dashboard_frame</value>
      <webElementGuid>23927947-80ff-4248-b93b-cf4824df2515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='expiryDate']</value>
      <webElementGuid>e946c64e-0226-4b3c-8111-73a690dff18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div/div/div[2]/div[2]/form/div[2]/div/div/input</value>
      <webElementGuid>0c792f7c-0a67-4d65-ae99-63e231a3c2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>3b8ff6f9-dad6-402d-accd-b6506be36b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'expiryDate' and @placeholder = 'MM / YYYY']</value>
      <webElementGuid>2e4dfb62-461b-480d-b5e6-27821826fba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
