<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_bluintouchapp</name>
   <tag></tag>
   <elementGuidId>3ccdf171-0346-4247-855b-45b025dd48a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'option-11')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs4__option-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs4__option-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7dee2202-a4bd-406f-988c-5beb1849544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-11</value>
      <webElementGuid>c1e6ebba-63fe-4cea-8a1a-3fc6d5e451e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b2e0c11b-047c-4402-a187-0539fed1c993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>5d832ada-3cbd-4d15-b6dd-2150f66f35e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd975bce-4f23-4dee-b310-005ef3702b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bluintouchapp
        </value>
      <webElementGuid>92e156e0-2879-4e34-afdb-905bc6934a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__option-12&quot;)</value>
      <webElementGuid>bda8a529-37ab-413a-a899-36deacf1a201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs4__option-12']</value>
      <webElementGuid>3f9cc3a9-2617-4ff9-b1f5-30415c0885de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs4__listbox']/li[13]</value>
      <webElementGuid>da4c91b0-50e1-4ee8-a0b2-15d9b2631591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='business_verification'])[1]/following::li[1]</value>
      <webElementGuid>7e59339d-ffb8-42e3-91f8-bb68f1e57a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='olas-app'])[1]/following::li[2]</value>
      <webElementGuid>08fbfca5-4c8a-4bae-b99e-a119766f9c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='liveness'])[1]/preceding::li[1]</value>
      <webElementGuid>e725d375-a3b0-4712-a793-75632ff2cc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test-sms-config'])[1]/preceding::li[2]</value>
      <webElementGuid>448809c0-1fd0-4d9e-ad94-f23b4451a86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bluintouchapp']/parent::*</value>
      <webElementGuid>a99f9f48-2712-455c-b9b0-c6693829b21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]</value>
      <webElementGuid>53d02031-c27d-4606-9077-1f3e7c4e03ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs4__option-12' and (text() = '
          bluintouchapp
        ' or . = '
          bluintouchapp
        ')]</value>
      <webElementGuid>be318372-8b26-4ed8-8fda-e56a03f6063c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
