<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Results fetched successfully</name>
   <tag></tag>
   <elementGuidId>8ca62fbd-e402-46ed-9650-95a47484dd89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T0tSZXN1bHRzJTIwZmV0Y2hlZCUyMHN1Y2Nlc3NmdWxseWdyZWVu']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.iziToast-message.slideIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>25c1eda3-9b7d-417f-a73a-56fb256808de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-message slideIn</value>
      <webElementGuid>e442224f-0351-4102-b18c-ded01d07322e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Results fetched successfully</value>
      <webElementGuid>262691c6-9c74-4f2b-9f11-5fae1fda9516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T0tSZXN1bHRzJTIwZmV0Y2hlZCUyMHN1Y2Nlc3NmdWxseWdyZWVu&quot;)/div[@class=&quot;iziToast-body&quot;]/div[@class=&quot;iziToast-texts&quot;]/p[@class=&quot;iziToast-message slideIn&quot;]</value>
      <webElementGuid>4b5c3f7e-acb0-4822-923f-ace3d2f208ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='T0tSZXN1bHRzJTIwZmV0Y2hlZCUyMHN1Y2Nlc3NmdWxseWdyZWVu']/div/div/p</value>
      <webElementGuid>852214db-b5b5-441f-9af9-69513e68518a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::p[1]</value>
      <webElementGuid>795b5255-494f-4498-b6f2-8fcfffcf2555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 BluSalt'])[1]/following::p[1]</value>
      <webElementGuid>600f98d4-6d3b-4300-b6a0-b21865bdd7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Results fetched successfully']/parent::*</value>
      <webElementGuid>5f05ef53-fcfa-45a9-bcbb-f36925c01810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/p</value>
      <webElementGuid>55dc96c2-cbb8-4398-ba20-d364caacad96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Results fetched successfully' or . = 'Results fetched successfully')]</value>
      <webElementGuid>6463dd90-9aa1-4046-a957-1d3702b4f21a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
