<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-control input-bordered w-100_1_2_3</name>
   <tag></tag>
   <elementGuidId>817af61d-ebc0-45f4-8401-d2fc2495507f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='createPaymentDispute']/div/div/div[2]/form/div[4]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex__start.input-wrapper.error > input.form-control.input-bordered.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaaf8aec-62de-4e65-a6e1-48b62fc53332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone Number</value>
      <webElementGuid>05489257-9099-4542-b31c-e83ca680c107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>f0c91f35-94c1-40ae-87cc-236c1755a2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-bordered w-100</value>
      <webElementGuid>3d6ded68-d6a4-4b49-9a73-865c5c1686f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createPaymentDispute&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;row h-100&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;flex__start input-wrapper   error&quot;]/input[@class=&quot;form-control input-bordered w-100&quot;]</value>
      <webElementGuid>4579256d-ee9c-402a-9321-56072a72d735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createPaymentDispute']/div/div/div[2]/form/div[4]/div/div[2]/input</value>
      <webElementGuid>1a4b32a8-8d23-4802-a9c9-2befc7727f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>c207f0ab-bee4-4718-84c3-6b4344508017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Phone Number']</value>
      <webElementGuid>48d1b622-e36b-4e54-b582-992d04d7774e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
