<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loading</name>
   <tag></tag>
   <elementGuidId>469b482a-aad3-45f8-b7cd-d46bdce78e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vs__actions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder=&quot;Select an application&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a7cf843-67ff-433f-be9f-4f8654eb05f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__actions</value>
      <webElementGuid>3c4f6e33-e910-4e0c-9b57-1c4a76778eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Loading...</value>
      <webElementGuid>daf04f12-e3cb-4466-b7c1-7ef1961f8d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__combobox&quot;)/div[@class=&quot;vs__actions&quot;]</value>
      <webElementGuid>feaf218f-790a-4097-b50a-48e546a72f1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs4__combobox']/div[2]</value>
      <webElementGuid>f6175e61-40c7-43ca-a63b-ee542af6a824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[4]</value>
      <webElementGuid>3d8671ac-485b-42b3-9542-ecbf1740a91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='identity-test'])[1]/preceding::div[2]</value>
      <webElementGuid>43d67179-56bf-4fb9-9470-e17e889e64d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]</value>
      <webElementGuid>6776baa3-b0fb-4ee5-bfe9-adba89b33b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Loading...' or . = '  Loading...')]</value>
      <webElementGuid>71141100-aad8-431c-a53d-2db6d2414170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
