<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1998</name>
   <tag></tag>
   <elementGuidId>cfd1e0ca-4ffd-4b3c-81f1-658b6339159e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vc-grid-cell.vc-grid-cell-row-3.vc-grid-cell-row--2.vc-grid-cell-col-1.vc-grid-cell-col--3 > span.vc-nav-item.is-inactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div/div[5]/div/span/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4ac98f4-ff6a-4976-8338-aa5c6caa3ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65b451f1-cf0a-4d2e-a332-590ea1adad14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>1998</value>
      <webElementGuid>31e92ba5-317f-4ce3-81e9-3aa173ba549d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a3090dcd-31a8-4d19-a63b-7ae62ec2d636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-nav-item is-inactive</value>
      <webElementGuid>f1b74776-1b7c-41fa-ad5e-8be6a1441b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1998 </value>
      <webElementGuid>4bc5a74b-2abd-48ff-9cb9-bac370b75046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;az-content-box&quot;]/div[@class=&quot;az-content-body tab-content&quot;]/div[1]/div[@class=&quot;col-12&quot;]/div[1]/div[@class=&quot;contact-details--card&quot;]/form[1]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/span[1]/div[@class=&quot;vc-popover-content-wrapper is-interactive&quot;]/div[@class=&quot;vc-popover-content direction-bottom vc-container&quot;]/div[@class=&quot;vc-container vc-blue&quot;]/div[@class=&quot;vc-pane-container&quot;]/div[@class=&quot;vc-grid-container grid&quot;]/div[@class=&quot;vc-grid-cell vc-grid-cell-row-1 vc-grid-cell-row--1 vc-grid-cell-col-1 vc-grid-cell-col--1&quot;]/div[@class=&quot;vc-pane&quot;]/div[@class=&quot;vc-header&quot;]/div[@class=&quot;vc-title-layout align-center&quot;]/div[@class=&quot;vc-title-wrapper&quot;]/div[@class=&quot;vc-popover-content-wrapper is-interactive&quot;]/div[@class=&quot;vc-popover-content direction-bottom vc-nav-popover-container&quot;]/div[@class=&quot;vc-nav-container&quot;]/div[@class=&quot;vc-grid-container&quot;]/div[@class=&quot;vc-grid-cell vc-grid-cell-row-3 vc-grid-cell-row--2 vc-grid-cell-col-1 vc-grid-cell-col--3&quot;]/span[@class=&quot;vc-nav-item is-inactive&quot;]</value>
      <webElementGuid>82e54b1e-01ba-48ab-8fd5-3afd87122520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div/div[5]/div/span/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div[7]/span</value>
      <webElementGuid>6558ef87-1c0d-47e7-bdd5-bd080bfb733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 2023'])[1]/following::span[10]</value>
      <webElementGuid>d89abaf3-89d9-46ea-a9f2-7856cd386b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[11]</value>
      <webElementGuid>a05dc2c9-60f7-414f-ba06-1f8be4012746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::span[7]</value>
      <webElementGuid>2f83432e-8ae8-4c0e-9661-608b9db00c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[1]/preceding::span[7]</value>
      <webElementGuid>3495d18e-c2f1-49a6-b30e-696b756581bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1998']/parent::*</value>
      <webElementGuid>a5155e22-59d6-4db7-b19d-b7ad66eaff17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span</value>
      <webElementGuid>39b94b51-1a59-4258-99b3-6c8c058b27f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 1998 ' or . = ' 1998 ')]</value>
      <webElementGuid>0d8eaff7-046a-4f40-91d9-368ef39736bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
