<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mar</name>
   <tag></tag>
   <elementGuidId>810ce8c9-1410-4ba9-8feb-4a7833cc729e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vc-grid-cell.vc-grid-cell-row-1.vc-grid-cell-row--4.vc-grid-cell-col-3.vc-grid-cell-col--1 > span.vc-nav-item.is-inactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div/div[5]/div/span/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d8fbb683-724e-48ee-8231-075ef242ad0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>523ee95f-fbb3-4e57-89cf-a6ebc7de24df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>March 2000</value>
      <webElementGuid>c6cb1c0f-ccf4-4802-814f-ef6ab22895e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a79eae66-7335-442e-aef1-2dc31991c50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-nav-item is-inactive</value>
      <webElementGuid>766523be-d9eb-4cd9-a5b6-2c3ef86e2d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Mar </value>
      <webElementGuid>e199ac34-caea-439f-8adf-732c1065a44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;az-content-box&quot;]/div[@class=&quot;az-content-body tab-content&quot;]/div[1]/div[@class=&quot;col-12&quot;]/div[1]/div[@class=&quot;contact-details--card&quot;]/form[1]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/span[1]/div[@class=&quot;vc-popover-content-wrapper is-interactive&quot;]/div[@class=&quot;vc-popover-content direction-bottom vc-container&quot;]/div[@class=&quot;vc-container vc-blue&quot;]/div[@class=&quot;vc-pane-container&quot;]/div[@class=&quot;vc-grid-container grid&quot;]/div[@class=&quot;vc-grid-cell vc-grid-cell-row-1 vc-grid-cell-row--1 vc-grid-cell-col-1 vc-grid-cell-col--1&quot;]/div[@class=&quot;vc-pane&quot;]/div[@class=&quot;vc-header&quot;]/div[@class=&quot;vc-title-layout align-center&quot;]/div[@class=&quot;vc-title-wrapper&quot;]/div[@class=&quot;vc-popover-content-wrapper is-interactive&quot;]/div[@class=&quot;vc-popover-content direction-bottom vc-nav-popover-container&quot;]/div[@class=&quot;vc-nav-container&quot;]/div[@class=&quot;vc-grid-container&quot;]/div[@class=&quot;vc-grid-cell vc-grid-cell-row-1 vc-grid-cell-row--4 vc-grid-cell-col-3 vc-grid-cell-col--1&quot;]/span[@class=&quot;vc-nav-item is-inactive&quot;]</value>
      <webElementGuid>0ffc336d-9ef2-4aaa-9d5f-655c4b328118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div[2]/div/div/div/div[2]/form/div/div[5]/div/span/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div[3]/span</value>
      <webElementGuid>09a81455-1b9b-45ef-9e83-58d699475349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb'])[1]/following::span[1]</value>
      <webElementGuid>c576708a-f497-4236-8f16-1efce1967e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/following::span[2]</value>
      <webElementGuid>0f847fc9-0f8d-4993-8843-636ee6598ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr'])[1]/preceding::span[1]</value>
      <webElementGuid>2697562b-957e-497f-afc7-466355fe7ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May'])[1]/preceding::span[2]</value>
      <webElementGuid>e96c8ebd-10e2-4f5c-809b-19a1d4d02958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mar']/parent::*</value>
      <webElementGuid>19dba374-fcf1-4cf4-96ad-0066e077a59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span</value>
      <webElementGuid>68281941-21be-4c14-81d8-f0c3182b4001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Mar ' or . = ' Mar ')]</value>
      <webElementGuid>fbb47be1-d75b-4456-b533-c957ae8cc43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
