<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_My Profile_pointer</name>
   <tag></tag>
   <elementGuidId>e2867c46-97bb-4690-8dd2-3e6257c6aa21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e106929-0d74-4216-bea6-77d65e2d054d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/icons/arrow-left.svg</value>
      <webElementGuid>1cea39fd-9d14-46ec-aa1a-2c4626d4b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9c3ad481-09a0-475c-9d06-43669f7b1c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>25ba3283-4812-46f9-a972-6bb0124cc375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;flex__between flex-wrap&quot;]/div[@class=&quot;SectionItem w-auto no-b-b mb-0 justify-content-start&quot;]/img[@class=&quot;pointer&quot;]</value>
      <webElementGuid>d84d1526-5adb-4f08-b8c1-21d74e92fe2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div/div/img</value>
      <webElementGuid>64352452-906c-4305-97b5-31ff930e97b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/img</value>
      <webElementGuid>04a0cd85-2bb9-4e76-af26-8d2db09e5693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/icons/arrow-left.svg']</value>
      <webElementGuid>fabbef8d-02c9-4eb0-8601-fcb7e455de37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
