<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__vs__selected-options</name>
   <tag></tag>
   <elementGuidId>22965047-0311-4cb1-95cc-123692451bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vs__selected-options</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs4__combobox']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dec2af1f-f8c5-461b-9fbc-9f1ed58992dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__selected-options</value>
      <webElementGuid>2bf554ad-4870-4406-8007-82d7b813a219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__combobox&quot;)/div[@class=&quot;vs__selected-options&quot;]</value>
      <webElementGuid>2d977e8c-6ff8-4151-bc77-64912bfd2824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs4__combobox']/div</value>
      <webElementGuid>f5f52136-68ec-4111-8b70-d2adafbf0820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>079b104c-f703-4b9b-b3c1-aab2b7b6c69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[1]</value>
      <webElementGuid>5041f9fb-8376-49ba-ba8c-82213a31bd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='identity-test'])[1]/preceding::div[3]</value>
      <webElementGuid>06031ef5-f391-4c9b-ab21-d6e65d0b42f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div</value>
      <webElementGuid>5ab25c94-746e-4239-b235-0d4944d8cebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
