<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_v2</name>
   <tag></tag>
   <elementGuidId>6c84f7ac-479d-4434-baa2-bb64dd517bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'option-1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs2__option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs2__option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>519f2064-5164-4b4b-b2f8-6287b89b8da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-1</value>
      <webElementGuid>ec86ee0d-178a-46c3-aaef-daedcd031a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0eedf5c2-4b4a-45a4-89e1-bc37afa80730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>37f2ff2c-abc5-4176-9981-564c5f66c2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b3c5be8-e075-4ced-9447-84c7ee6194c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          v2
        </value>
      <webElementGuid>3cbca50f-ec35-4c02-b785-befac61ff23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs2__option-1&quot;)</value>
      <webElementGuid>e1030607-f434-49c9-bfed-ed6db5265fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs2__option-1']</value>
      <webElementGuid>2d846e72-e4cf-42ee-b0a9-424bc8076960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs2__listbox']/li[2]</value>
      <webElementGuid>99a7a1a3-b33b-4d1a-a6ad-6bdd77893e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1'])[1]/following::li[1]</value>
      <webElementGuid>e91e608e-6b28-42d6-9e4d-b3fefc17772b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::li[2]</value>
      <webElementGuid>4ba74f31-92ac-497e-9d52-c0ccc833d89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API version field is required.'])[1]/preceding::li[1]</value>
      <webElementGuid>8988e2ff-20c2-4fc4-9796-3ac768b0db72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency Type'])[1]/preceding::li[2]</value>
      <webElementGuid>473087d6-8f1e-41d5-ab78-5833ae700848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='v2']/parent::*</value>
      <webElementGuid>e053cc75-7d87-42a0-aa9e-e2c4fa601571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]</value>
      <webElementGuid>29814c3b-1574-4213-a5fc-02fc8a3eb914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs2__option-1' and (text() = '
          v2
        ' or . = '
          v2
        ')]</value>
      <webElementGuid>3d3c9b8b-39e9-41f7-b782-fc7e33124634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
