<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_an_application</name>
   <tag></tag>
   <elementGuidId>6e93266d-c78b-4cdc-b5f3-2a5948fce924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vs__selected-options</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder=&quot;Select Application&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f84d5ed-8354-4ae3-8e27-512f256db76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__selected-options</value>
      <webElementGuid>55551c06-6d46-43ac-8871-224ed8502af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs1__combobox&quot;)/div[@class=&quot;vs__selected-options&quot;]</value>
      <webElementGuid>68dcfda1-625f-4c89-8f7d-3e24808d0871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs1__combobox']/div</value>
      <webElementGuid>492d437b-1a83-41f1-a290-c69eeb5d7064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[3]</value>
      <webElementGuid>25e841c4-2009-4cf7-bfb2-ee73e846091a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[1]</value>
      <webElementGuid>8b1f65c2-a09d-4d34-b68a-3816b3a62624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='identity-test'])[1]/preceding::div[3]</value>
      <webElementGuid>e7dcdd40-fd92-4d6f-8b48-c9e0359ae92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div</value>
      <webElementGuid>aa7bcce7-650c-479d-9bf0-67fb9ac439f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
