<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_application</name>
   <tag></tag>
   <elementGuidId>b66cc776-145c-4070-b0d6-b07afa38cca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs4__combobox']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vs__actions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>404e5744-636a-4f5e-b85c-c07a7e9b5ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__actions</value>
      <webElementGuid>4855dffc-be0b-4db2-9bb1-ee1062ee35df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Loading...</value>
      <webElementGuid>c4b2e79e-d053-4dd4-bdb8-6580eea3b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__combobox&quot;)/div[@class=&quot;vs__actions&quot;]</value>
      <webElementGuid>b8fa4da0-0a25-4785-8069-57187db8fda3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs4__combobox']/div[2]</value>
      <webElementGuid>ea0ac714-a2be-4f17-991a-c91826caea44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[4]</value>
      <webElementGuid>a4957118-796c-4181-b17c-cb6bb4fead84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application field is required.'])[1]/preceding::div[2]</value>
      <webElementGuid>1e607b4f-5543-49d4-a87d-dda13749420a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>fe575d6e-f4a4-4d51-9a61-aefe9d6d3626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Loading...' or . = '  Loading...')]</value>
      <webElementGuid>2194a558-8898-44ac-813b-16710663b53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
