<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit Application</name>
   <tag></tag>
   <elementGuidId>3e397923-d98e-40fc-87ce-fb3664321abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='applications']/div/div/div[2]/div[2]/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb829305-08d6-456c-9709-aeba254b7eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>367b155c-3b90-4456-852f-0802381e41a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-effect</name>
      <type>Main</type>
      <value>effect-scale</value>
      <webElementGuid>17ab8758-0a3a-4e33-8c71-b2d149986234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-backdrop</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>a2a26bfa-1ddc-4730-af4c-9cf899e1bfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#editApplication</value>
      <webElementGuid>2c650822-27d1-4c8c-accd-8503f74bfc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>0b46586c-8e95-4d0d-a85d-e3f6901c22e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Edit Application
                      </value>
      <webElementGuid>10a54f92-be9b-4cae-9aaa-17837a058b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;active&quot;)/div[@class=&quot;col-lg-12&quot;]/div[@id=&quot;applications&quot;]/div[@class=&quot;app-key-item-wrapper accordion-item&quot;]/div[@class=&quot;app-key-list-item accordion-heading&quot;]/div[@class=&quot;flex__between w-100&quot;]/div[@class=&quot;app-key-action-wrap ellipsis show&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>fa01ee2a-3a9e-4e2b-be84-bbe8d9e56608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='applications']/div/div/div[2]/div[2]/div/a[3]</value>
      <webElementGuid>e2c47868-249b-43fd-8099-d6c87256c7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit Application')]</value>
      <webElementGuid>4c29a875-4a43-4c92-ba13-96711df5a67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Services'])[1]/following::a[1]</value>
      <webElementGuid>453da3c9-b1ac-4322-9626-4a9ae7b9868c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regenerate key'])[1]/following::a[2]</value>
      <webElementGuid>bf3ec792-5d41-4e03-a611-74e9a938af64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate App'])[1]/preceding::a[1]</value>
      <webElementGuid>6e402283-18c5-4202-9e04-733476e414cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Application']/parent::*</value>
      <webElementGuid>f7f9e775-0d3c-4b54-948a-0d01c27cbb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[44]</value>
      <webElementGuid>8e160db3-7aa1-4aaf-940d-eb9ea185a792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[3]</value>
      <webElementGuid>a5b827f0-7922-412e-baa1-7b3f83dbce7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                        Edit Application
                      ' or . = '
                        Edit Application
                      ')]</value>
      <webElementGuid>ad8dc36e-3dd4-4c22-bc9b-ff38a05fa5ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
