<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_API KEY_dropdown-title_1</name>
   <tag></tag>
   <elementGuidId>2879d014-a547-4bef-ab2c-395cda1902b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='applications']/div/div/div[2]/div[2]/span)[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>feedb641-bbf6-4e8b-99b5-c5c4589ce34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d70d92df-da0b-49da-9443-1209d64a0c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>28f87b8c-38f3-4d36-8519-a806c34421b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-title</value>
      <webElementGuid>5a7d77a0-cdf7-4c7c-b1da-9e282c6d1e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57828fda-0dc6-446e-8a30-4f518c9cdad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;active&quot;)/div[@class=&quot;col-lg-12&quot;]/div[@id=&quot;applications&quot;]/div[@class=&quot;app-key-item-wrapper accordion-item&quot;]/div[@class=&quot;app-key-list-item accordion-heading collapsed&quot;]/div[@class=&quot;flex__between w-100&quot;]/div[@class=&quot;app-key-action-wrap ellipsis&quot;]/span[@class=&quot;dropdown-title&quot;]</value>
      <webElementGuid>3b1f51f2-68b6-49c1-b735-3db65d27d493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='applications']/div/div/div[2]/div[2]/span)[7]</value>
      <webElementGuid>40c5e03a-d66b-4465-b6f4-f7a08a1a5c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div[2]/span</value>
      <webElementGuid>3f8b7b0d-b25d-4892-badd-ea19c55a36ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
