<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_API KEY_dropdown-title</name>
   <tag></tag>
   <elementGuidId>937c4073-2daf-4c54-a7a1-5f2186e3281d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='applications']/div/div/div[2]/div[2]/span)[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;active&quot;)/div[@class=&quot;col-lg-12&quot;]/div[@id=&quot;applications&quot;]/div[@class=&quot;app-key-item-wrapper accordion-item&quot;]/div[@class=&quot;app-key-list-item accordion-heading&quot;]/div[@class=&quot;flex__between w-100&quot;]/div[@class=&quot;app-key-action-wrap ellipsis&quot;]/span[@class=&quot;dropdown-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6864fc85-391c-42ba-acd5-092ee03b76f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58c08429-b6bb-46af-b4c9-b7604d35b40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>5c8628dc-5796-44b2-8628-58f16cda471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-title</value>
      <webElementGuid>3eebad84-2f96-4a28-b355-308304610eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b7cf9c3-6afa-446f-ac84-21d398a3d5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;active&quot;)/div[@class=&quot;col-lg-12&quot;]/div[@id=&quot;applications&quot;]/div[@class=&quot;app-key-item-wrapper accordion-item&quot;]/div[@class=&quot;app-key-list-item accordion-heading&quot;]/div[@class=&quot;flex__between w-100&quot;]/div[@class=&quot;app-key-action-wrap ellipsis&quot;]/span[@class=&quot;dropdown-title&quot;]</value>
      <webElementGuid>346b92b7-a2ab-4a17-84c4-7a5e5bd9b052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='applications']/div/div/div[2]/div[2]/span)[7]</value>
      <webElementGuid>4c9667a1-1406-4c5e-8a2a-d3e66e9aa7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div[2]/span</value>
      <webElementGuid>c51e3be0-5f5a-4fc8-adc2-a5b35360a1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='applications']/div/div/div[2]/div[2]/span</value>
      <webElementGuid>06531921-a141-4883-b365-be2fcb8acaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div[2]/div[2]/span</value>
      <webElementGuid>8dd0a3e4-be8b-4b98-83b8-69258863084d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
