<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your File is Successfully Uploaded</name>
   <tag></tag>
   <elementGuidId>1b1fa49b-ba44-4efe-94d5-7cbe1e99347e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.iziToast-message.slideIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T0tZb3VyJTIwRmlsZSUyMGlzJTIwU3VjY2Vzc2Z1bGx5JTIwVXBsb2FkZWRncmVlbg']/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7b5ff3e5-9d1d-4e4a-a0ce-95d71009e00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iziToast-message slideIn</value>
      <webElementGuid>129754ae-dcc0-4cbc-8b13-3730ca2775d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your File is Successfully Uploaded</value>
      <webElementGuid>66448b26-d98a-49e6-a011-a47092af456d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T0tZb3VyJTIwRmlsZSUyMGlzJTIwU3VjY2Vzc2Z1bGx5JTIwVXBsb2FkZWRncmVlbg&quot;)/div[@class=&quot;iziToast-body&quot;]/div[@class=&quot;iziToast-texts&quot;]/p[@class=&quot;iziToast-message slideIn&quot;]</value>
      <webElementGuid>013b43a9-565e-4612-aed4-098ea38c3915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='T0tZb3VyJTIwRmlsZSUyMGlzJTIwU3VjY2Vzc2Z1bGx5JTIwVXBsb2FkZWRncmVlbg']/div/div/p</value>
      <webElementGuid>d2dacf2c-b7d0-4e5e-a134-274b6804ad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::p[1]</value>
      <webElementGuid>96370ae4-8c75-46fc-848c-894056de66c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 BluSalt'])[1]/following::p[1]</value>
      <webElementGuid>a4f04416-eb15-4911-95ea-d75fe97bb35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your File is Successfully Uploaded']/parent::*</value>
      <webElementGuid>c0d858b9-7833-4f46-b7e9-5142c1f87aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/p</value>
      <webElementGuid>19b1cd27-8a33-4977-a891-c967c9244186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your File is Successfully Uploaded' or . = 'Your File is Successfully Uploaded')]</value>
      <webElementGuid>74257638-11c3-4091-a04a-bd6f5ad48c73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
