<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__vs__selected-options_1_2</name>
   <tag></tag>
   <elementGuidId>ee1bf9c3-0cdd-456f-bf5c-6e7ccf58c28e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs20__combobox']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs20__combobox > div.vs__selected-options</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e813dfe2-b5a1-44c7-a01d-84ba8e4d536e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__selected-options</value>
      <webElementGuid>ee5ed392-8877-432f-b9cd-313b5c6bf822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs20__combobox&quot;)/div[@class=&quot;vs__selected-options&quot;]</value>
      <webElementGuid>2fd547b1-2425-41fb-a68f-2133836ccd1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs20__combobox']/div</value>
      <webElementGuid>aec57e0f-f694-4000-a4dc-57ab270380e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>f08a7cca-15b7-4356-a5b6-e464eed419e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Wallet'])[1]/following::div[3]</value>
      <webElementGuid>251e8392-5059-4f62-8660-dca0b2b457eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/preceding::div[1]</value>
      <webElementGuid>c49846c1-e720-47d0-9193-2bfdc738f34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>ee7c65cf-295e-4f3f-b67c-7db492183d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
