<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_My Profile_pointer</name>
   <tag></tag>
   <elementGuidId>d3e93c06-042d-4762-8fe8-e74b97e14e01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elBody']/div[2]/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8cba6496-46e7-4ee1-a22d-1e2b4ef5e4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/icons/arrow-left.svg</value>
      <webElementGuid>7e0e57b6-9f8a-409b-bba3-57ca62f0539b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3d7e4b09-5aef-4991-b72f-2ab1c44206e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>ba1cb452-01ea-4dc0-b099-5edbed877b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elBody&quot;)/div[@class=&quot;az-content az-content-dashboard-nine&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;SectionItem no-b-b mb-4 flex__beteen flex-wrap&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/img[@class=&quot;pointer&quot;]</value>
      <webElementGuid>36899936-8fd6-4b0d-9e9b-7578e0cca8e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elBody']/div[2]/div[2]/div/div/img</value>
      <webElementGuid>ab0eefa0-6c34-47ee-a3f1-e096e07db731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>42d1b9a3-c1b1-47f7-8859-710fd9575416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/icons/arrow-left.svg']</value>
      <webElementGuid>2698f1ad-813b-4e86-9c0b-ad8498566727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
