<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Yanga Plan</name>
   <tag></tag>
   <elementGuidId>546afcfe-8878-4cb2-944e-a642f9233182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs3__option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vs3__option-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'option-1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3f833452-e2e9-45c2-855e-f9ed3a0a2778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-1</value>
      <webElementGuid>aec6795a-db7d-4f39-bdd8-3c0e3cf82713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c94c0b49-7796-492a-9015-168d330a0d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>3964e0c2-8573-461f-8c60-398508e7f049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf104d45-8681-4aa5-8a28-a6ef1a510de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Yanga Plan
        </value>
      <webElementGuid>c04b6dfe-44b8-45d1-9fc1-622b3607424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs3__option-1&quot;)</value>
      <webElementGuid>86928be7-e916-417c-ac21-3636043b0277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs3__option-1']</value>
      <webElementGuid>c96f491f-b350-4456-b82b-88d5203f3469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs3__listbox']/li[2]</value>
      <webElementGuid>e63c7173-b4dc-4e37-8d12-caa08c78118d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Plans'])[1]/following::li[1]</value>
      <webElementGuid>343649de-8dc0-4fdb-ba92-a17a3c2361d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[2]</value>
      <webElementGuid>e321dc13-49dd-4852-ac44-9e1846f41c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST'])[1]/preceding::li[1]</value>
      <webElementGuid>510f46d9-38c5-4c94-9def-0389022a581d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bonanza'])[1]/preceding::li[2]</value>
      <webElementGuid>84e12f5e-e7b3-4be2-9f97-075773649910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yanga Plan']/parent::*</value>
      <webElementGuid>13f291cc-5a27-40a9-8fff-d66050cf0c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/ul/li[2]</value>
      <webElementGuid>a19bc580-f73f-42e4-a349-0683ec880c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs3__option-1' and (text() = '
          Yanga Plan
        ' or . = '
          Yanga Plan
        ')]</value>
      <webElementGuid>d8af033b-2374-4377-af56-ca7caf42da70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
